seed: 9061

dataset:
  dat_dir: ???
  resolution: 1
  data_device: cpu
  frameset_type: imavatar
  num_for_train: -350  # INSTA style split for train/test
  cameras_extent: 1.0

model:
  # (experimental) please set pipe.convert_SHs_python=True if sh_degree>0
  sh_degree: 0 
  num_init_samples: 10000
  xyz_as_uvd: True # use _xyz as variables of uvd
  with_mesh_scaling: True
  #max_n_gauss: 300000

pipe:
  convert_SHs_python: False
  compute_cov3D_python: False
  debug: False

optim:
  optim_xyz:
    lr: 0.00016
    scheduler_args:
      lr_init: 0.00016
      lr_final: 0.0000016
      lr_delay_mult: 0.01
      lr_max_steps: ${optim.total_iteration}
  optim_features:
    lr: 0.0025
  optim_opacity:
    lr: 0.05
  optim_scaling:
    lr: 0.005
  optim_rotation:
    lr: 0.001
    
  total_iteration: 30000
  save_every_iter: 30000
  testing_iterations: [ 30000 ]
    
  densify_from_iter: 600
  densification_interval: 100
  densify_until_iter: 29_000
  opacity_reset_start_iter: 0
  opacity_reset_interval: 3000
  
  size_threshold: 20
  densify_grad_threshold: 0.0002
  min_opacity: 0.005
  
  lambda_rgb_mse: 10.0
  lambda_ssim: 0.0
  lambda_perceptual: 0.01
  lambda_scaling: 0.0           # 0.0 for head, 1.0 for instant avatar
  thresh_scaling_max: 0.008
  thresh_scaling_ratio: 10.0
  lambda_sparsity: 0.0

  # triangle walk
  triangle_walk_interval: 100

  #scheduler:
  #  milestone: 2000
  #  decay: 0.33






